version: "3.9"

services:

  rabbitmq:
    container_name: rabbitmq
    env_file:
        - .env
    ports:
        - 15672:15672 # port for management UI 
        - 5672:5672
    build: 
      context: .
      dockerfile: Infrastructure/RabbitMQ/Dockerfile


  consul:
    container_name: consul
    ports:
      - 8500:8500 # port for UI/API calls
      - 8400:8400
      - 8600:8600
      - 8600:8600/udp 
    build: 
      context: .
      dockerfile: Infrastructure/Consul/Dockerfile

  vault:
    container_name: vault
    image: vault
    env_file:
      - .env
    environment:
        VAULT_ADDR: "http://127.0.0.1:8200"
        VAULT_TOKEN: "vault-distribt-token" # to be able to use the cli on dev
        VAULT_DEV_ROOT_TOKEN_ID: "vault-distribt-token"
    cap_add:
      - IPC_LOCK
    ports:
        - "8200:8200"
    volumes:
        - ./Infrastructure/Vault/vault_init.sh:/vault/config/vault_init.sh
        - ./Infrastructure/Vault/vault_init.sh:/vault/config/vault.hcl
    entrypoint:
      - sh
      - -c
      - |
        chmod +x /vault/config/vault_init.sh &&
        vault server -dev &
        sleep 10 &&
        /bin/ash vault/config/vault_init.sh &&
        sleep infinity
    restart: on-failure
    depends_on:
      - rabbitmq
      - consul

  guildmanagersc:
    container_name: GuildManagerSC
    env_file:
      - .env
    ports:
       - 7000:80
    build:
      context: .
      dockerfile: src/GuildManagerSC/Dockerfile
    restart: on-failure 

  mandrilapi:
    container_name: MandrilAPI
    env_file:
      - .env
    ports:
      - 7002:80
    build:
      context: .
      dockerfile: MandrilAPI/src/MandrilAPI/Dockerfile
    restart: on-failure 

#networks:
#  SCGuildManagerNetwork:
#    driver: bridge
#networks:
#  SCGuildManagerNetwork:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 172.25.0.0/16
#        - gateway: 172.25.0.1