version: "3.9"

services:

  consul:
    container_name: consul
    ports:
      - 8500:8500 # port for UI/API calls
      - 8400:8400
      - 8600:8600
      - 8600:8600/udp 
    build: 
      context: .
      dockerfile: Infrastructure/Consul/Dockerfile
    mem_limit: 50m
    restart: on-failure 

  rabbitmq:
    container_name: rabbitmq
    env_file:
        - .env
    ports:
        - 15672:15672 # port for management UI 
        - 5672:5672
    build: 
      context: .
      dockerfile: Infrastructure/RabbitMQ/Dockerfile
    mem_limit: 200m
    restart: on-failure 

  vault:
      container_name: vault
      env_file:
        - .env
      ports:
        - 8200:8200
      environment:
          VAULT_TOKEN: "${VAULT_TOKEN}" #needed to use the cli on dev
          VAULT_DEV_ROOT_TOKEN_ID: "${VAULT_TOKEN}"
      build: 
          context: .
          dockerfile: Infrastructure/Vault/Dockerfile
      mem_limit: 50m
      restart: on-failure 
      cap_add:
        - IPC_LOCK

  ###############################
  # Microservices configuration #
  ###############################

  api-gateway:
    container_name: APIGateway
    env_file:
      - .env
    ports:
       - 7000:80
    build:
      context: .
      dockerfile: src/APIGateway/Dockerfile
    mem_limit: 150m
    restart: on-failure  

  mandrilapi:
    container_name: MandrilAPI
    env_file:
      - .env
    ports:
      - 7002:80
    build:
      context: .
      dockerfile: MandrilAPI/src/MandrilAPI/Dockerfile
    mem_limit: 200m
    restart: on-failure 

  ###################################
  # Microservices configuration end #
  ###################################
