version: "3.9"

services:

  rabbitmq:
    container_name: rabbitmq
    env_file:
        - .env
    ports:
        - 15672:15672
        - 5672:5672
    build: 
      context: .
      dockerfile: Infrastructure\RabbitMQ\Dockerfile


  vault:
    container_name: vault
    env_file:
      - .env
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
      VAULT_TOKEN: "${ValutToken}" # to be able to use the cli on dev
      VAULT_DEV_ROOT_TOKEN_ID: "${ValutToken}"
    ports:
      - 8200:8200
    image: vault:latest
    volumes: 
        - ./Infrastructure/Vault/vault_init.sh:/vault/config/vault_init.sh
    restart: on-failure 
    depends_on:
      - rabbitmq

  guildmanagersc:
    container_name: GuildManagerSC
    env_file:
      - .env
    ports:
       - 7000:80
    build:
      context: .
      dockerfile: src/GuildManagerSC/Dockerfile
    restart: on-failure 

  mandrilapi:
    container_name: MandrilAPI
    env_file:
      - .env
    ports:
      - 7002:80
    build:
      context: .
      dockerfile: MandrilAPI/src/MandrilAPI/Dockerfile
    restart: on-failure 


networks:
  default:
    name: SCGuildManagerNetwork
    driver: bridge