version: '3.4'

services:

  rabbitmq:
    image: rabbitmq:3.11.11-management-alpine
    container_name: rabbitmq
    ports:
        - 15672:15672
        - 5672:5672

  vault:
    container_name: vault
    env_file:
      - .env
    environment:
      VAULT_ADDR: "http://localhost:7001"
      VAULT_TOKEN: "${ValutToken}" # to be able to use the cli on dev
      VAULT_DEV_ROOT_TOKEN_ID: "${ValutToken}"
    ports:
      - 7001:8200
    image: vault:latest
    restart: on-failure 
    depends_on:
      - rabbitmq

  guildmanagersc:
    container_name: GuildManagerSC
    env_file:
      - .env
    ports:
       - 7000:80
    build:
      context: .
      dockerfile: src/GuildManagerSC/Dockerfile
    restart: on-failure 

  mandrilapi:
    container_name: MandrilAPI
    env_file:
      - .env
    ports:
      - 7002:80
    build:
      context: .
      dockerfile: MandrilAPI\src\MandrilAPI\Dockerfile
    restart: on-failure 


networks:
  default:
    name: SCGuildManagerNetwork
    driver: bridge